package com.wk.kill.model.entity;

import java.util.Date;

public class Item {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.id
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.name
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.code
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.stock
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.purchase_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Date purchaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.is_active
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.create_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.update_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.id
     *
     * @return the value of item.id
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.id
     *
     * @param id the value for item.id
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.name
     *
     * @return the value of item.name
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.name
     *
     * @param name the value for item.name
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.code
     *
     * @return the value of item.code
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.code
     *
     * @param code the value for item.code
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.stock
     *
     * @return the value of item.stock
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.stock
     *
     * @param stock the value for item.stock
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setStock(Long stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.purchase_time
     *
     * @return the value of item.purchase_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Date getPurchaseTime() {
        return purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.purchase_time
     *
     * @param purchaseTime the value for item.purchase_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.is_active
     *
     * @return the value of item.is_active
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.is_active
     *
     * @param isActive the value for item.is_active
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.create_time
     *
     * @return the value of item.create_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.create_time
     *
     * @param createTime the value for item.create_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.update_time
     *
     * @return the value of item.update_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.update_time
     *
     * @param updateTime the value for item.update_time
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}