package com.wk.kill.model.entity;

public class RandomCode {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_code.id
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column random_code.code
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_code.id
     *
     * @return the value of random_code.id
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_code.id
     *
     * @param id the value for random_code.id
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column random_code.code
     *
     * @return the value of random_code.code
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column random_code.code
     *
     * @param code the value for random_code.code
     *
     * @mbggenerated Wed Sep 16 15:03:46 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}